# Generated by Django 4.1.5 on 2023-01-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYMapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='_from',
            field=models.DateField(auto_now_add=True),
        ),
    ]
